- name: Play Level Variable
  hosts: localhost
  vars:
   password: hello
  tasks:
    - name: display msg
      ansible.builtin.debug:
        msg: password--{{ password }}

    - name: playlevel variable can use in tasks level
      ansible.builtin.debug:
        msg: password--{{ password }}
