- name: conditions
  hosts: localhosts
  tasks:
    - name: ansible facts
      ansible.builtin.shell: ansible_hosts
        register: res_hosts

    - name: display ansible hosts
      ansible.builtin.debug:
        msg: "{{ res_hosts }}"


