- name: conditions
  hosts: localhosts
  tasks:
    - name: ansible facts
      ansible.builtin.gather_facts:
        register: "{{ ansible_hosts "}}"

    - name: display ansible hosts
      ansible.builtin.debug:
        msg: "{{ ansible_hosts }}"


