- name: tags
  hosts: localhost
  become: yes
  tags: nginx
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: display uptime
      ansible.builtin.shell: uptime
      register: output

    - name: display uptime
      ansible.builtin.debug:
        msg: "{{output}}"




