- name: "backend"
  hosts: backend-dev.pdevops72.online
  become: yes
  tasks:
    - name: "disable nodejs"
      ansible.builtin.package:
        name: "nodejs"
        state: absent

    - name: "enable nodejs"
      ansible.builtin.package:
        name: "nodejs"
        state: present

    - name: "Install nodejs"
      ansible.builtin.dnf:
        name: "nodejs"
        state: installed

    - name: "Add application user"
      ansible.builtin.user:
        name: expense

    - name: "clean the code"
      ansible.builtin.file:
        path: /app
        state: directory



