- name: "Install nginx"
  hosts: frontend-dev.pdevops72.online
  become: yes
  tasks:
    - name: "statrt nginx installation"
      ansible.builtin.dnf:
        name: "nginx"
        state: latest

    - name: "start nginx service"
      ansible.builtin.systemd_service:
        name: "nginx"
        state: started
