- name: store output in register keyword
  hosts: all
  tasks:
    - name: store output
      ansible.builtin.shell: uptime
      register: result

    - name: display uptime
      ansible.builtin.debug:
        msg: "{{ result }}"