format_version: 10
pipelines:
  rolespipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/PavaniVemasani18/devops
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - test-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test-job:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - expense.yml
                command: ansible-playbook
                run_if: passed
